# Generated by Django 5.1.2 on 2025-04-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_center', '0002_alter_notificationlog_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='from_system',
            field=models.TextField(default='condo_notification'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='message',
            field=models.JSONField(),
        ),
    ]
