# Generated by Django 5.1.2 on 2025-04-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_center', '0003_notificationlog_from_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='from_system',
            field=models.TextField(default='schedule_condo_notification'),
        ),
    ]
